//! Pure-Zig MySQL/MariaDB connection: a blocking TCP socket driven by the
//! `protocol.zig` codec. No libmysqlclient, no std.net (this stripped 0.16
//! std lacks it) — TCP is opened via `std.c` getaddrinfo + socket + connect,
//! exactly like `core.tls.boring_outbound.dialBlocking`, and bytes move with
//! `std.c.read`/`std.c.write`.
//!
//! Flow: connect → read HandshakeV10 → send HandshakeResponse41 (with the
//! mysql_native_password token) → expect OK. Thereafter `query`/`exec` use
//! the text protocol (COM_QUERY); `prepare`+`executePrepared` use the binary
//! protocol (COM_STMT_PREPARE/EXECUTE/CLOSE). Each command resets the packet
//! sequence id to 0 (the protocol numbers packets within a command/response
//! exchange).
//!
//! Tiger Style: a single fixed `recv_buf` (16 MiB cap mirrors the default
//! max_allowed_packet) holds the current packet; rows are streamed to a
//! caller callback so no unbounded buffering. Reads loop on short
//! `std.c.read` returns until a full packet (header length) is in hand.

const std = @import("std");
const proto = @import("protocol.zig");
const openssl = @import("../../crypto/openssl.zig");
const ossl = openssl.c;

pub const Error = error{
    DnsFailed,
    ConnectFailed,
    SocketError,
    WriteFailed,
    ReadFailed,
    /// Server sent an ERR packet. The code/sqlstate are stashed on the
    /// connection (`last_err`) for the backend to classify.
    ServerError,
    /// A packet didn't have the shape we expected for this phase.
    ProtocolError,
    /// Auth plugin the server demanded isn't supported, or full-auth was
    /// required over a channel where we can't satisfy it.
    UnsupportedAuth,
    PacketTooLarge,
    Truncated,
    Unsupported,
    /// TLS upgrade was requested (tls=require) but the handshake failed,
    /// the server didn't advertise CLIENT_SSL, or OAEP/cert work failed.
    TlsFailed,
};

/// How the connection treats transport security.
pub const TlsMode = enum {
    /// Plain TCP. caching_sha2 full-auth (if the server demands it) uses
    /// the RSA-public-key exchange to protect the password.
    disabled,
    /// Upgrade to TLS via SSLRequest before sending credentials. Over TLS,
    /// caching_sha2 full-auth sends the cleartext password (no RSA).
    require,
};

/// Largest single packet we will buffer (MySQL's default max_allowed_packet
/// for the protocol is 16 MiB minus a byte; we cap the read buffer here).
pub const max_packet: usize = 16 * 1024 * 1024;

/// Connection parameters (parsed from a URL by the provider).
pub const Options = struct {
    host: []const u8 = "127.0.0.1",
    port: u16 = 3306,
    username: []const u8 = "root",
    password: []const u8 = "",
    database: []const u8 = "",
    timeout_ms: u32 = 5000,
    /// Transport security. `?tls=require` in the URL sets this to `.require`.
    tls: TlsMode = .disabled,
};

/// Captured server error, surfaced after a `ServerError`.
pub const ServerErr = struct {
    code: u16 = 0,
    sqlstate: [5]u8 = .{ 0, 0, 0, 0, 0 },
    has_sqlstate: bool = false,
};

/// A decoded result column value handed to row callbacks. Slices alias the
/// connection's `recv_buf` and are only valid for the duration of the call.
pub const Value = union(enum) {
    null_,
    int: i64,
    real: f64,
    str: []const u8,
};

pub const max_columns: usize = 16;

pub const Row = struct {
    values: [max_columns]Value = undefined,
    count: u8 = 0,
};

pub const RowCallback = *const fn (ctx: *anyopaque, row: *const Row) bool;

pub const Conn = struct {
    fd: std.c.fd_t,
    seq: u8 = 0,
    last_err: ServerErr = .{},
    last_affected: u64 = 0,
    last_insert_id: u64 = 0,
    /// Owns the per-packet receive buffer (heap, allocated once at connect).
    recv_buf: []u8,
    allocator: std.mem.Allocator,
    /// Reusable scratch for command encoding (bounded; large enough for a
    /// COM_STMT_EXECUTE with text/blob params up to a few KiB — bigger
    /// statements aren't generated by the ORM's CRUD paths).
    send_buf: []u8,
    /// OpenSSL session + context once the channel is upgraded to TLS.
    /// Null on a plain-TCP connection. After upgrade, all packet I/O goes
    /// through `SSL_read`/`SSL_write` instead of `std.c.read`/`write`.
    ssl: ?*ossl.SSL = null,
    ssl_ctx: ?*ossl.SSL_CTX = null,

    pub fn connect(allocator: std.mem.Allocator, opts: Options) Error!*Conn {
        const fd = try dialBlocking(opts.host, opts.port, opts.timeout_ms);
        errdefer _ = std.c.close(fd);

        const recv = allocator.alloc(u8, max_packet) catch return error.SocketError;
        errdefer allocator.free(recv);
        const send = allocator.alloc(u8, 1 * 1024 * 1024) catch return error.SocketError;
        errdefer allocator.free(send);

        const self = allocator.create(Conn) catch return error.SocketError;
        errdefer allocator.destroy(self);
        self.* = .{
            .fd = fd,
            .recv_buf = recv,
            .send_buf = send,
            .allocator = allocator,
        };
        errdefer self.teardownTls();

        try self.handshake(opts);
        return self;
    }

    pub fn close(self: *Conn) void {
        self.teardownTls();
        _ = std.c.close(self.fd);
        self.allocator.free(self.recv_buf);
        self.allocator.free(self.send_buf);
        self.allocator.destroy(self);
    }

    fn teardownTls(self: *Conn) void {
        if (self.ssl) |ssl| {
            _ = ossl.SSL_shutdown(ssl);
            ossl.SSL_free(ssl);
            self.ssl = null;
        }
        if (self.ssl_ctx) |ctx| {
            ossl.SSL_CTX_free(ctx);
            self.ssl_ctx = null;
        }
    }

    // ── Handshake ────────────────────────────────────────────────────────

    /// The three auth plugins we can satisfy. `mysql_native_password`
    /// (pre-8.0 default + MariaDB) and `caching_sha2_password` (MySQL 8.0
    /// default). An empty handshake plugin name is treated as native.
    const AuthPlugin = enum { native, caching_sha2 };

    fn classifyPlugin(name: []const u8) Error!AuthPlugin {
        if (name.len == 0 or std.mem.eql(u8, name, "mysql_native_password")) return .native;
        if (std.mem.eql(u8, name, "caching_sha2_password")) return .caching_sha2;
        return error.UnsupportedAuth;
    }

    fn handshake(self: *Conn, opts: Options) Error!void {
        const payload = try self.readPacket();
        const hs = proto.parseHandshake(payload) catch return error.ProtocolError;

        const plugin = try classifyPlugin(hs.authPluginName());

        // ── Optional TLS upgrade ──────────────────────────────────────
        // Per protocol the SSLRequest reuses the handshake sequence id
        // (it's the client's first reply), so we do NOT reset self.seq
        // before sending it; writePacket continues numbering from the
        // server handshake (seq 0 → our reply seq 1).
        if (opts.tls == .require) {
            if (hs.capabilities & proto.CLIENT_SSL == 0) return error.TlsFailed;
            try self.sendSslRequest(opts);
            try self.upgradeToTls(opts);
        }

        // ── HandshakeResponse41 with the initial-plugin token ─────────
        const scramble = hs.scramble();
        try self.sendAuthResponse(opts, plugin, scramble);

        // ── Auth result / continuation state machine ──────────────────
        try self.finishAuth(opts, plugin, scramble);
    }

    /// Build + send the HandshakeResponse41 carrying the auth token for
    /// `plugin` computed over `nonce` (the server's handshake scramble).
    fn sendAuthResponse(self: *Conn, opts: Options, plugin: AuthPlugin, nonce: []const u8) Error!void {
        var w = proto.Writer.init(self.send_buf);
        switch (plugin) {
            .native => {
                var token: [20]u8 = undefined;
                const n = proto.nativePasswordScramble(opts.password, nonce, &token);
                proto.encodeHandshakeResponse(&w, .{
                    .username = opts.username,
                    .auth_response = token[0..n],
                    .database = opts.database,
                    .auth_plugin = "mysql_native_password",
                    .with_tls = (self.ssl != null),
                }) catch return error.ProtocolError;
            },
            .caching_sha2 => {
                var token: [proto.caching_sha2_token_len]u8 = undefined;
                const n = proto.cachingSha2PasswordScramble(opts.password, nonce, &token);
                proto.encodeHandshakeResponse(&w, .{
                    .username = opts.username,
                    .auth_response = token[0..n],
                    .database = opts.database,
                    .auth_plugin = "caching_sha2_password",
                    .with_tls = (self.ssl != null),
                }) catch return error.ProtocolError;
            },
        }
        try self.writePacket(w.slice());
    }

    /// Drive the post-HandshakeResponse exchange to a terminal OK/ERR.
    /// Handles caching_sha2 AuthMoreData (fast-auth success / full-auth
    /// required) and a single AuthSwitchRequest.
    fn finishAuth(self: *Conn, opts: Options, plugin: AuthPlugin, nonce: []const u8) Error!void {
        var cur_plugin = plugin;
        var cur_nonce_buf: [proto.max_scramble]u8 = undefined;
        const ncopy = @min(nonce.len, cur_nonce_buf.len);
        @memcpy(cur_nonce_buf[0..ncopy], nonce[0..ncopy]);
        var cur_nonce_len = ncopy;
        var switched = false;

        while (true) {
            const resp = try self.readPacket();
            // OK / ERR are terminal in every phase.
            switch (proto.classify(resp)) {
                .ok => return,
                .err => {
                    self.captureErr(resp);
                    return error.ServerError;
                },
                .eof => {
                    // AuthSwitchRequest (0xfe + plugin + nonce). Honour it
                    // once; a second switch is treated as a protocol fault.
                    if (switched) return error.UnsupportedAuth;
                    switched = true;
                    const sw = proto.parseAuthSwitch(resp) catch return error.ProtocolError;
                    cur_plugin = try classifyPlugin(sw.plugin());
                    const sn = sw.nonce();
                    const c2 = @min(sn.len, cur_nonce_buf.len);
                    @memcpy(cur_nonce_buf[0..c2], sn[0..c2]);
                    cur_nonce_len = c2;
                    // The reply continues the running packet sequence id
                    // (managed by write/readPacket); no reset here.
                    try self.sendAuthSwitchResponse(opts, cur_plugin, cur_nonce_buf[0..cur_nonce_len]);
                    continue;
                },
                .other => {
                    // AuthMoreData (0x01 ...) — only meaningful for
                    // caching_sha2. Any other plugin sending it is a fault.
                    if (cur_plugin != .caching_sha2) return error.ProtocolError;
                    const more = proto.parseAuthMoreData(resp) catch return error.ProtocolError;
                    if (more.len == 0) return error.ProtocolError;
                    switch (more[0]) {
                        proto.CACHING_SHA2_FAST_AUTH_SUCCESS => {
                            // The trailing OK packet follows; loop to read it.
                            continue;
                        },
                        proto.CACHING_SHA2_PERFORM_FULL_AUTH => {
                            try self.cachingSha2FullAuth(opts, cur_nonce_buf[0..cur_nonce_len]);
                            continue;
                        },
                        else => return error.ProtocolError,
                    }
                },
            }
        }
    }

    /// Reply to an AuthSwitchRequest by recomputing the token for the
    /// switched-to plugin over the freshly-issued nonce.
    fn sendAuthSwitchResponse(self: *Conn, opts: Options, plugin: AuthPlugin, nonce: []const u8) Error!void {
        var w = proto.Writer.init(self.send_buf);
        switch (plugin) {
            .native => {
                var token: [20]u8 = undefined;
                const n = proto.nativePasswordScramble(opts.password, nonce, &token);
                w.bytes(token[0..n]) catch return error.ProtocolError;
            },
            .caching_sha2 => {
                var token: [proto.caching_sha2_token_len]u8 = undefined;
                const n = proto.cachingSha2PasswordScramble(opts.password, nonce, &token);
                w.bytes(token[0..n]) catch return error.ProtocolError;
            },
        }
        try self.writePacket(w.slice());
    }

    /// caching_sha2 full authentication (server returned 0x04). Over TLS we
    /// send the cleartext password (NUL-terminated). Over plaintext we ask
    /// the server for its RSA public key (request byte 0x02), receive the
    /// PEM, and send RSA-OAEP( password XOR nonce ).
    fn cachingSha2FullAuth(self: *Conn, opts: Options, nonce: []const u8) Error!void {
        if (self.ssl != null) {
            // Cleartext password over the encrypted channel, NUL-terminated.
            var w = proto.Writer.init(self.send_buf);
            w.bytes(opts.password) catch return error.PacketTooLarge;
            w.writeByte(0) catch return error.PacketTooLarge;
            try self.writePacket(w.slice());
            return;
        }

        // Plaintext channel: request the server RSA public key.
        {
            var w = proto.Writer.init(self.send_buf);
            w.writeByte(proto.CACHING_SHA2_REQUEST_PUBLIC_KEY) catch return error.ProtocolError;
            try self.writePacket(w.slice());
        }
        // Server replies with AuthMoreData(0x01) + PEM public key.
        const key_pkt = try self.readPacket();
        const pem = proto.parseAuthMoreData(key_pkt) catch return error.ProtocolError;
        if (pem.len == 0) return error.UnsupportedAuth;

        // Obfuscate the (NUL-terminated) password with the nonce, then
        // RSA-OAEP-encrypt under the server key.
        var xored: [512]u8 = undefined;
        const xlen = proto.xorPasswordWithNonce(opts.password, nonce, &xored) catch return error.UnsupportedAuth;

        var ct: [1024]u8 = undefined;
        const ct_len = openssl.rsaEncryptOaepFromPublicPem(pem, xored[0..xlen], &ct) catch return error.TlsFailed;

        var w = proto.Writer.init(self.send_buf);
        w.bytes(ct[0..ct_len]) catch return error.PacketTooLarge;
        try self.writePacket(w.slice());
    }

    /// Encode + send an SSLRequest packet (the 32-byte HandshakeResponse41
    /// prefix with CLIENT_SSL set). Sent on the plaintext socket before the
    /// TLS handshake; continues the handshake sequence id.
    fn sendSslRequest(self: *Conn, opts: Options) Error!void {
        var w = proto.Writer.init(self.send_buf);
        proto.encodeSSLRequest(&w, opts.database.len > 0, @intCast(max_packet), 0x21) catch return error.ProtocolError;
        try self.writePacket(w.slice());
    }

    /// Upgrade the live fd to a TLS client session via OpenSSL. After this
    /// returns, packet I/O routes through SSL_read/SSL_write. We do not
    /// verify the peer certificate here (DB endpoints are typically pinned
    /// by network topology / private CA); the goal of tls=require is to
    /// encrypt the channel so caching_sha2 full-auth can send cleartext.
    fn upgradeToTls(self: *Conn, opts: Options) Error!void {
        openssl.ensureLibraryInit();
        const ctx = ossl.SSL_CTX_new(ossl.TLS_client_method()) orelse return error.TlsFailed;
        errdefer ossl.SSL_CTX_free(ctx);
        ossl.SSL_CTX_set_verify(ctx, ossl.SSL_VERIFY_NONE, null);

        const ssl = ossl.SSL_new(ctx) orelse return error.TlsFailed;
        errdefer ossl.SSL_free(ssl);
        if (ossl.SSL_set_fd(ssl, @intCast(self.fd)) != 1) return error.TlsFailed;

        // SNI: hand the server the requested hostname.
        var host_z: [256]u8 = undefined;
        if (opts.host.len < host_z.len) {
            @memcpy(host_z[0..opts.host.len], opts.host);
            host_z[opts.host.len] = 0;
            _ = ossl.SSL_ctrl(
                ssl,
                ossl.SSL_CTRL_SET_TLSEXT_HOSTNAME,
                ossl.TLSEXT_NAMETYPE_host_name,
                @ptrCast(&host_z),
            );
        }

        if (ossl.SSL_connect(ssl) != 1) return error.TlsFailed;

        self.ssl = ssl;
        self.ssl_ctx = ctx;
    }

    // ── Text protocol: exec (no rows) + query (streamed rows) ──────────────

    /// Execute a statement, discarding any result set. Sets last_affected /
    /// last_insert_id from the OK packet.
    pub fn exec(self: *Conn, sql: []const u8) Error!void {
        self.seq = 0;
        var w = proto.Writer.init(self.send_buf);
        proto.encodeQuery(&w, sql) catch return error.PacketTooLarge;
        try self.writePacket(w.slice());

        const first = try self.readPacket();
        switch (proto.classify(first)) {
            .ok => {
                const ok = proto.parseOk(first) catch return error.ProtocolError;
                self.last_affected = ok.affected_rows;
                self.last_insert_id = ok.last_insert_id;
                return;
            },
            .err => {
                self.captureErr(first);
                return error.ServerError;
            },
            // A result set: drain it (column defs, rows, terminating EOF/OK).
            .other => return self.drainTextResult(first),
            .eof => return error.ProtocolError,
        }
    }

    /// Execute a text-protocol query and stream each row to `cb`.
    pub fn query(self: *Conn, sql: []const u8, ctx: *anyopaque, cb: RowCallback) Error!void {
        self.seq = 0;
        var w = proto.Writer.init(self.send_buf);
        proto.encodeQuery(&w, sql) catch return error.PacketTooLarge;
        try self.writePacket(w.slice());

        const first = try self.readPacket();
        switch (proto.classify(first)) {
            .ok => {
                const ok = proto.parseOk(first) catch return error.ProtocolError;
                self.last_affected = ok.affected_rows;
                self.last_insert_id = ok.last_insert_id;
                return; // no rows
            },
            .err => {
                self.captureErr(first);
                return error.ServerError;
            },
            .other => {},
            .eof => return error.ProtocolError,
        }

        const col_count: usize = @intCast(proto.parseColumnCount(first) catch return error.ProtocolError);
        var cols: [max_columns]proto.ColumnDef = undefined;
        try self.readColumnDefs(col_count, &cols);

        // Text-protocol rows until EOF/OK.
        while (true) {
            const pkt = try self.readPacket();
            switch (proto.classify(pkt)) {
                .eof, .ok => return,
                .err => {
                    self.captureErr(pkt);
                    return error.ServerError;
                },
                .other => {
                    var row: Row = .{};
                    var r = proto.Reader.init(pkt);
                    const n = @min(col_count, max_columns);
                    var i: usize = 0;
                    while (i < n) : (i += 1) {
                        const field = proto.parseTextField(&r) catch return error.ProtocolError;
                        row.values[i] = if (field) |s| textValue(cols[i].type_code, s) else .null_;
                    }
                    row.count = @intCast(n);
                    if (!cb(ctx, &row)) return;
                },
            }
        }
    }

    // ── Binary protocol: prepared statements ───────────────────────────────

    pub const Stmt = struct {
        id: u32,
        num_params: u16,
        num_columns: u16,
    };

    pub fn prepare(self: *Conn, sql: []const u8) Error!Stmt {
        self.seq = 0;
        var w = proto.Writer.init(self.send_buf);
        proto.encodePrepare(&w, sql) catch return error.PacketTooLarge;
        try self.writePacket(w.slice());

        const resp = try self.readPacket();
        switch (proto.classify(resp)) {
            .err => {
                self.captureErr(resp);
                return error.ServerError;
            },
            .ok => {},
            else => return error.ProtocolError,
        }
        const ok = proto.parsePrepareOk(resp) catch return error.ProtocolError;
        // Consume the parameter-definition packets (+ EOF) and the column-
        // definition packets (+ EOF) that follow PREPARE_OK.
        try self.skipDefs(ok.num_params);
        try self.skipDefs(ok.num_columns);
        return .{ .id = ok.statement_id, .num_params = ok.num_params, .num_columns = ok.num_columns };
    }

    pub fn closeStmt(self: *Conn, stmt: Stmt) void {
        self.seq = 0;
        var w = proto.Writer.init(self.send_buf);
        proto.encodeStmtClose(&w, stmt.id) catch return;
        // COM_STMT_CLOSE has no response; best-effort.
        self.writePacket(w.slice()) catch {};
    }

    /// Execute a prepared statement that returns no rows. Updates
    /// last_affected / last_insert_id.
    pub fn execPrepared(self: *Conn, stmt: Stmt, params: []const proto.Param) Error!void {
        try self.sendExecute(stmt, params);
        const first = try self.readPacket();
        switch (proto.classify(first)) {
            .ok => {
                const ok = proto.parseOk(first) catch return error.ProtocolError;
                self.last_affected = ok.affected_rows;
                self.last_insert_id = ok.last_insert_id;
            },
            .err => {
                self.captureErr(first);
                return error.ServerError;
            },
            // Returned a result set unexpectedly — drain binary rows.
            .other => try self.drainBinaryResult(stmt, first, null, null),
            .eof => return error.ProtocolError,
        }
    }

    /// Execute a prepared statement and stream its (binary) rows to `cb`.
    pub fn queryPrepared(self: *Conn, stmt: Stmt, params: []const proto.Param, ctx: *anyopaque, cb: RowCallback) Error!void {
        try self.sendExecute(stmt, params);
        const first = try self.readPacket();
        switch (proto.classify(first)) {
            .ok => {
                const ok = proto.parseOk(first) catch return error.ProtocolError;
                self.last_affected = ok.affected_rows;
                self.last_insert_id = ok.last_insert_id;
                return;
            },
            .err => {
                self.captureErr(first);
                return error.ServerError;
            },
            .other => try self.drainBinaryResult(stmt, first, ctx, cb),
            .eof => return error.ProtocolError,
        }
    }

    // (drainBinaryResult below takes an optional callback so execPrepared
    //  can reuse it to discard an unexpected result set.)

    fn sendExecute(self: *Conn, stmt: Stmt, params: []const proto.Param) Error!void {
        self.seq = 0;
        var w = proto.Writer.init(self.send_buf);
        proto.encodeStmtExecute(&w, stmt.id, params) catch return error.PacketTooLarge;
        try self.writePacket(w.slice());
    }

    fn drainBinaryResult(self: *Conn, stmt: Stmt, first: []const u8, ctx: ?*anyopaque, cb: ?RowCallback) Error!void {
        _ = stmt;
        const col_count: usize = @intCast(proto.parseColumnCount(first) catch return error.ProtocolError);
        var cols: [max_columns]proto.ColumnDef = undefined;
        try self.readColumnDefs(col_count, &cols);

        const n = @min(col_count, max_columns);
        while (true) {
            const pkt = try self.readPacket();
            // In the binary protocol a row begins with 0x00; an EOF/OK
            // terminates. classify treats a 0x00-lead, ≥? packet as `.ok`
            // only when it parses as OK — but binary rows also start 0x00.
            // Disambiguate: EOF (0xfe,<9) ends; otherwise it's a row.
            switch (proto.classify(pkt)) {
                .eof => return,
                .err => {
                    self.captureErr(pkt);
                    return error.ServerError;
                },
                else => {
                    const callback = cb orelse continue; // exec-style drain
                    const cctx = ctx orelse continue;
                    var values: [max_columns]proto.BinaryValue = undefined;
                    proto.parseBinaryRow(pkt, cols[0..n], values[0..n]) catch return error.ProtocolError;
                    var row: Row = .{ .count = @intCast(n) };
                    var i: usize = 0;
                    while (i < n) : (i += 1) {
                        row.values[i] = switch (values[i]) {
                            .null_ => .null_,
                            .int => |v| .{ .int = v },
                            .real => |v| .{ .real = v },
                            .str => |s| .{ .str = s },
                        };
                    }
                    if (!callback(cctx, &row)) return;
                },
            }
        }
    }

    fn drainTextResult(self: *Conn, first: []const u8) Error!void {
        const col_count: usize = @intCast(proto.parseColumnCount(first) catch return error.ProtocolError);
        var cols: [max_columns]proto.ColumnDef = undefined;
        try self.readColumnDefs(col_count, &cols);
        while (true) {
            const pkt = try self.readPacket();
            switch (proto.classify(pkt)) {
                .eof, .ok => return,
                .err => {
                    self.captureErr(pkt);
                    return error.ServerError;
                },
                .other => {}, // a row; discard
            }
        }
    }

    /// Read `n` ColumnDefinition41 packets into `out`, then consume the
    /// trailing EOF (unless the server set CLIENT_DEPRECATE_EOF — we don't
    /// advertise it, so an EOF is always present after the defs).
    fn readColumnDefs(self: *Conn, n: usize, out: *[max_columns]proto.ColumnDef) Error!void {
        var i: usize = 0;
        while (i < n) : (i += 1) {
            const pkt = try self.readPacket();
            const cd = proto.parseColumnDef(pkt) catch return error.ProtocolError;
            if (i < max_columns) out[i] = cd;
        }
        // Terminating EOF after the column definitions.
        const eof = try self.readPacket();
        if (proto.classify(eof) == .err) {
            self.captureErr(eof);
            return error.ServerError;
        }
    }

    /// Skip `n` definition packets plus the trailing EOF (used to consume
    /// the param-def and column-def blocks after PREPARE_OK). When `n` is 0
    /// the server omits the EOF too.
    fn skipDefs(self: *Conn, n: u16) Error!void {
        if (n == 0) return;
        var i: u16 = 0;
        while (i < n) : (i += 1) _ = try self.readPacket();
        _ = try self.readPacket(); // EOF
    }

    fn captureErr(self: *Conn, payload: []const u8) void {
        const e = proto.parseErr(payload) catch {
            self.last_err = .{};
            return;
        };
        self.last_err = .{ .code = e.code, .has_sqlstate = e.has_sqlstate };
        if (e.has_sqlstate) @memcpy(&self.last_err.sqlstate, e.sqlstate_buf[0..5]);
    }

    // ── Packet I/O ─────────────────────────────────────────────────────────

    /// Read one full protocol packet payload into `recv_buf`, returning a
    /// slice of it. Validates the 4-byte header and accumulates the body
    /// across short reads. The sequence id is checked for monotonicity but
    /// not enforced beyond bumping `self.seq`.
    fn readPacket(self: *Conn) Error![]const u8 {
        var hdr: [proto.header_len]u8 = undefined;
        try self.readExact(&hdr);
        const h = proto.decodeHeader(&hdr) catch return error.ProtocolError;
        if (h.length > self.recv_buf.len) return error.PacketTooLarge;
        self.seq = h.seq +% 1;
        const body = self.recv_buf[0..h.length];
        try self.readExact(body);
        return body;
    }

    fn writePacket(self: *Conn, payload: []const u8) Error!void {
        if (payload.len > 0xff_ffff) return error.PacketTooLarge;
        var hdr: [proto.header_len]u8 = undefined;
        proto.encodeHeader(&hdr, payload.len, self.seq);
        self.seq +%= 1;
        try self.writeAll(&hdr);
        try self.writeAll(payload);
    }

    fn readExact(self: *Conn, buf: []u8) Error!void {
        var off: usize = 0;
        while (off < buf.len) {
            if (self.ssl) |ssl| {
                const n = ossl.SSL_read(ssl, buf.ptr + off, @intCast(buf.len - off));
                if (n <= 0) return error.ReadFailed;
                off += @intCast(n);
            } else {
                const n = std.c.read(self.fd, buf.ptr + off, buf.len - off);
                if (n <= 0) return error.ReadFailed;
                off += @intCast(n);
            }
        }
    }

    fn writeAll(self: *Conn, buf: []const u8) Error!void {
        var off: usize = 0;
        while (off < buf.len) {
            if (self.ssl) |ssl| {
                const n = ossl.SSL_write(ssl, buf.ptr + off, @intCast(buf.len - off));
                if (n <= 0) return error.WriteFailed;
                off += @intCast(n);
            } else {
                const n = std.c.write(self.fd, buf.ptr + off, buf.len - off);
                if (n <= 0) return error.WriteFailed;
                off += @intCast(n);
            }
        }
    }
};

/// MySQL TEXT-protocol fields are always sent as strings. Coerce numeric
/// columns back to int/real so callers see typed values matching the binary
/// protocol; everything else stays a string slice.
fn textValue(type_code: u8, s: []const u8) Value {
    return switch (type_code) {
        proto.MYSQL_TYPE_TINY,
        proto.MYSQL_TYPE_SHORT,
        proto.MYSQL_TYPE_LONG,
        proto.MYSQL_TYPE_LONGLONG,
        => if (std.fmt.parseInt(i64, s, 10)) |v| .{ .int = v } else |_| .{ .str = s },
        proto.MYSQL_TYPE_FLOAT,
        proto.MYSQL_TYPE_DOUBLE,
        => if (std.fmt.parseFloat(f64, s)) |v| .{ .real = v } else |_| .{ .str = s },
        else => .{ .str = s },
    };
}

/// Resolve host:port and open a blocking TCP socket via getaddrinfo +
/// socket + connect, trying each address until one connects. Mirrors
/// `core.tls.boring_outbound.dialBlocking`. Applies SO_RCVTIMEO/SNDTIMEO.
fn dialBlocking(host: []const u8, port: u16, timeout_ms: u32) Error!std.c.fd_t {
    var host_z: [256]u8 = undefined;
    if (host.len >= host_z.len) return error.DnsFailed;
    @memcpy(host_z[0..host.len], host);
    host_z[host.len] = 0;

    var port_buf: [8]u8 = undefined;
    const port_str = std.fmt.bufPrint(&port_buf, "{d}", .{port}) catch return error.DnsFailed;
    port_buf[port_str.len] = 0;

    var hints: std.c.addrinfo = std.mem.zeroes(std.c.addrinfo);
    hints.family = std.c.AF.UNSPEC;
    hints.socktype = std.c.SOCK.STREAM;

    const host_ptr: [*:0]const u8 = @ptrCast(&host_z);
    const port_ptr: [*:0]const u8 = @ptrCast(&port_buf);
    var res: ?*std.c.addrinfo = null;
    const rc = std.c.getaddrinfo(host_ptr, port_ptr, &hints, &res);
    if (@intFromEnum(rc) != 0) return error.DnsFailed;
    const head = res orelse return error.DnsFailed;
    defer std.c.freeaddrinfo(head);

    var ai = res;
    while (ai) |a| : (ai = a.next) {
        const addr = a.addr orelse continue;
        const fd = std.c.socket(@intCast(a.family), @intCast(a.socktype), @intCast(a.protocol));
        if (fd < 0) continue;
        applyTimeouts(fd, timeout_ms);
        if (std.c.connect(fd, addr, a.addrlen) == 0) return fd;
        _ = std.c.close(fd);
    }
    return error.ConnectFailed;
}

fn applyTimeouts(fd: std.c.fd_t, timeout_ms: u32) void {
    if (timeout_ms == 0) return;
    const tv = std.posix.timeval{
        .sec = @intCast(timeout_ms / 1000),
        .usec = @intCast((timeout_ms % 1000) * 1000),
    };
    const bytes = std.mem.asBytes(&tv);
    std.posix.setsockopt(fd, std.posix.SOL.SOCKET, std.posix.SO.RCVTIMEO, bytes) catch {};
    std.posix.setsockopt(fd, std.posix.SOL.SOCKET, std.posix.SO.SNDTIMEO, bytes) catch {};
}

// ──────────────────────────────────────────────────────────────────────
// Tests — these exercise the *pure* helpers reachable without a socket.
// Live connect tests live in mysql_backend.zig (gated on MYSQL_TEST_URL).
// ──────────────────────────────────────────────────────────────────────

const testing = std.testing;

test "textValue: numeric coercion mirrors binary protocol typing" {
    try testing.expectEqual(@as(i64, -42), textValue(proto.MYSQL_TYPE_LONG, "-42").int);
    try testing.expectEqual(@as(i64, 9001), textValue(proto.MYSQL_TYPE_LONGLONG, "9001").int);
    try testing.expectApproxEqAbs(@as(f64, 3.5), textValue(proto.MYSQL_TYPE_DOUBLE, "3.5").real, 1e-9);
    // A VARCHAR stays a string slice.
    try testing.expectEqualStrings("hi", textValue(proto.MYSQL_TYPE_VAR_STRING, "hi").str);
    // A malformed numeric falls back to the raw string rather than crashing.
    try testing.expectEqualStrings("notnum", textValue(proto.MYSQL_TYPE_LONG, "notnum").str);
}

test "dialBlocking: unresolvable host fails cleanly (no hang, no crash)" {
    // A syntactically-valid but unroutable .invalid TLD must surface
    // DnsFailed/ConnectFailed quickly, never block the suite.
    const r = dialBlocking("nonexistent.invalid", 3306, 500);
    try testing.expectError(error.DnsFailed, r);
}
