//! Schema migrations — a versioned, ordered set of DDL steps plus a
//! standalone runner that applies them over a `zorm.Backend`.
//!
//! Model (deliberately NOT auto-diff): the initial `CREATE TABLE` for an
//! entity is generated by `initialMigration`; later schema changes are
//! hand-authored `Migration`s composed from the `ddl` builder helpers
//! (`addColumn`/`createIndex`/`dropColumn`/…) with explicit ids. No DB
//! introspection — deterministic and dialect-correct.
//!
//! A `Migration.up` is a LIST of single statements (not one `;`-joined
//! string): the backend execs one prepared statement at a time, and a host
//! that prefers its own multi-statement runner can join the list trivially.
//!
//! `Migrator` mirrors the host's `schema.applyAll`: it bootstraps a
//! `zorm_migrations` tracking table, applies un-applied migrations in
//! ascending id order, each inside one `backend.transaction`, and records
//! the id on success. Idempotent (by id); a failing migration rolls back
//! and is not recorded. Time is caller-supplied (`now_unix`) — the stripped
//! 0.16 std has no wall clock.

const std = @import("std");
const contract = @import("contract.zig");
const reflect = @import("reflect.zig");
const ddl = @import("ddl.zig");

const Backend = contract.Backend;
const Error = contract.Error;
const Dialect = contract.Dialect;
const BindValue = contract.BindValue;

/// Upper bound on migrations in one `run` (Tiger Style: bounded ordering
/// buffer). Matches the host `Schema`'s capacity.
pub const max_migrations: usize = 256;

/// One versioned schema change. `up`/`down` are lists of single statements.
pub const Migration = struct {
    /// Globally unique, strictly increasing. Convention: namespace by a
    /// prefix per subsystem, as the host does.
    id: u32,
    name: []const u8,
    up: []const []const u8,
    /// Optional inverse (recorded for ops; the runtime never auto-applies it).
    down: ?[]const []const u8 = null,
};

/// The initial migration for entity `T`: `CREATE TABLE` (with FK clauses)
/// plus one index per foreign-key column. `down` drops the table.
pub fn initialMigration(comptime T: type, id: u32, dialect: Dialect) Migration {
    return .{
        .id = id,
        .name = comptime reflect.TableInfo(T).table ++ ":create",
        .up = switch (dialect) {
            inline else => |d| comptime buildInitialUp(T, d),
        },
        .down = comptime &.{ddl.dropTable(T)},
    };
}

fn buildInitialUp(comptime T: type, comptime dialect: Dialect) []const []const u8 {
    const out = comptime blk: {
        const idx = ddl.foreignKeyIndexes(T, dialect);
        var up: [1 + idx.len][]const u8 = undefined;
        up[0] = ddl.createTable(T, dialect);
        for (idx, 0..) |s, i| up[i + 1] = s;
        break :blk up;
    };
    return &out;
}

/// Applies ordered migrations over a `zorm.Backend`, tracked in a
/// `zorm_migrations` table. Dialect-aware (tracking DDL + bind placeholders).
pub const Migrator = struct {
    /// Apply every not-yet-applied migration (ascending id), each in its own
    /// transaction; record each on success. Idempotent by id.
    pub fn run(backend: Backend, migrations: []const Migration, now_unix: i64) Error!void {
        if (migrations.len > max_migrations) return Error.BackendFailed;
        try ensureTable(backend);

        // Apply in ascending id order without mutating the caller's slice.
        var order: [max_migrations]usize = undefined;
        for (0..migrations.len) |i| order[i] = i;
        var i: usize = 1;
        while (i < migrations.len) : (i += 1) {
            var j = i;
            while (j > 0 and migrations[order[j - 1]].id > migrations[order[j]].id) : (j -= 1) {
                const t = order[j];
                order[j] = order[j - 1];
                order[j - 1] = t;
            }
        }

        for (order[0..migrations.len]) |idx| {
            const m = &migrations[idx];
            if (try isApplied(backend, m.id)) continue;
            var ctx = RunCtx{ .backend = backend, .mig = m, .now = now_unix, .ins_sql = insertSql(backend.dialect) };
            try backend.transaction(&ctx, RunCtx.body);
        }
    }

    const RunCtx = struct {
        backend: Backend,
        mig: *const Migration,
        now: i64,
        ins_sql: []const u8,

        fn body(ptr: *anyopaque) Error!void {
            const c: *RunCtx = @ptrCast(@alignCast(ptr));
            for (c.mig.up) |stmt| try c.backend.exec(stmt, &.{});
            try c.backend.exec(c.ins_sql, &.{
                .{ .int = @intCast(c.mig.id) },
                .{ .text = c.mig.name },
                .{ .int = c.now },
            });
        }
    };

    fn ensureTable(backend: Backend) Error!void {
        const sql = switch (backend.dialect) {
            .sqlite => "CREATE TABLE IF NOT EXISTS zorm_migrations (id INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at INTEGER NOT NULL)",
            .postgres => "CREATE TABLE IF NOT EXISTS zorm_migrations (id BIGINT PRIMARY KEY, name TEXT NOT NULL, applied_at BIGINT NOT NULL)",
            .mysql => "CREATE TABLE IF NOT EXISTS zorm_migrations (id BIGINT PRIMARY KEY, name VARCHAR(255) NOT NULL, applied_at BIGINT NOT NULL)",
            .mssql => "IF OBJECT_ID(N'zorm_migrations', N'U') IS NULL CREATE TABLE zorm_migrations (id BIGINT PRIMARY KEY, name NVARCHAR(255) NOT NULL, applied_at BIGINT NOT NULL)",
        };
        try backend.exec(sql, &.{});
    }

    fn isApplied(backend: Backend, id: u32) Error!bool {
        const sql = switch (backend.dialect) {
            .sqlite, .mysql => "SELECT 1 FROM zorm_migrations WHERE id = ?",
            .postgres => "SELECT 1 FROM zorm_migrations WHERE id = $1",
            .mssql => "SELECT 1 FROM zorm_migrations WHERE id = @p1",
        };
        var row: contract.Row = .{};
        return backend.queryOne(sql, &.{.{ .int = @intCast(id) }}, &row);
    }

    fn insertSql(dialect: Dialect) []const u8 {
        return switch (dialect) {
            .sqlite, .mysql => "INSERT INTO zorm_migrations (id, name, applied_at) VALUES (?, ?, ?)",
            .postgres => "INSERT INTO zorm_migrations (id, name, applied_at) VALUES ($1, $2, $3)",
            .mssql => "INSERT INTO zorm_migrations (id, name, applied_at) VALUES (@p1, @p2, @p3)",
        };
    }
};

// ── Tests ──────────────────────────────────────────────────────────────

const testing = std.testing;
const fields = @import("fields.zig");
const mock = @import("testing.zig");
const relations = @import("relations.zig");

const User = struct {
    pub const zorm_table = "m_users";
    id: fields.Pk(64) = .{},
    name: fields.Text(64) = .{},
};
const Post = struct {
    pub const zorm_table = "m_posts";
    id: fields.Pk(64) = .{},
    author_id: fields.Text(64) = .{},
    body: fields.Text(128) = .{},
    author: relations.BelongsTo(User, "author_id", .{ .on_delete = .cascade }) = .{},
};

test "initialMigration: table create + FK index, drop in down" {
    const m = initialMigration(Post, 2001, .sqlite);
    try testing.expectEqual(@as(u32, 2001), m.id);
    try testing.expectEqualStrings("m_posts:create", m.name);
    // up: CREATE TABLE (with FK), then the FK index.
    try testing.expectEqual(@as(usize, 2), m.up.len);
    try testing.expect(std.mem.startsWith(u8, m.up[0], "CREATE TABLE IF NOT EXISTS \"m_posts\" ("));
    try testing.expect(std.mem.indexOf(u8, m.up[0], "FOREIGN KEY (\"author_id\") REFERENCES \"m_users\" (\"id\") ON DELETE CASCADE") != null);
    try testing.expectEqualStrings("CREATE INDEX IF NOT EXISTS \"ix_m_posts_author_id\" ON \"m_posts\" (\"author_id\")", m.up[1]);
    try testing.expect(m.down != null);
    try testing.expectEqualStrings("DROP TABLE IF EXISTS m_posts", m.down.?[0]);
}

test "initialMigration: no-FK entity has a single up statement" {
    const m = initialMigration(User, 2000, .postgres);
    try testing.expectEqual(@as(usize, 1), m.up.len);
    try testing.expect(std.mem.indexOf(u8, m.up[0], "CREATE TABLE IF NOT EXISTS \"m_users\"") != null);
}

test "Migrator: applies an ordered set + is idempotent by id" {
    var db = mock.MockBackend.init();
    const backend = db.backend(.sqlite);

    const migs = [_]Migration{
        initialMigration(User, 2000, .sqlite),
        initialMigration(Post, 2001, .sqlite),
        // a hand-authored evolution step using the ddl helper
        .{ .id = 2002, .name = "m_users:add_bio", .up = &.{ddl.addColumn(struct {
            pub const zorm_table = "m_users";
            id: fields.Pk(64) = .{},
            name: fields.Text(64) = .{},
            bio: fields.Text(128) = .{},
        }, "bio", .sqlite)} },
    };

    try Migrator.run(backend, &migs, 1_700_000_000);
    // All three recorded.
    inline for (.{ 2000, 2001, 2002 }) |id| {
        var row: contract.Row = .{};
        try testing.expect(try backend.queryOne("SELECT 1 FROM zorm_migrations WHERE id = ?", &.{.{ .int = id }}, &row));
    }

    // Re-running is a no-op: the count stays 3 (idempotent by id).
    try Migrator.run(backend, &migs, 1_700_000_001);
    var cnt: contract.Row = .{};
    try testing.expect(try backend.queryOne("SELECT id FROM zorm_migrations WHERE id = ?", &.{.{ .int = 2002 }}, &cnt));
}

test "Migrator: applies in ascending id order regardless of input order" {
    var db = mock.MockBackend.init();
    const backend = db.backend(.sqlite);
    // Deliberately out of order; Post (FK) before User would fail under FK
    // enforcement, so ordering must sort by id (User=2000 before Post=2001).
    const migs = [_]Migration{
        initialMigration(Post, 2001, .sqlite),
        initialMigration(User, 2000, .sqlite),
    };
    try Migrator.run(backend, &migs, 1_700_000_000);
    var row: contract.Row = .{};
    try testing.expect(try backend.queryOne("SELECT 1 FROM zorm_migrations WHERE id = ?", &.{.{ .int = 2000 }}, &row));
    try testing.expect(try backend.queryOne("SELECT 1 FROM zorm_migrations WHERE id = ?", &.{.{ .int = 2001 }}, &row));
}

test "Migrator: a failing migration rolls back and is not recorded" {
    var db = mock.MockBackend.init();
    const backend = db.backend(.sqlite);
    const migs = [_]Migration{
        initialMigration(User, 2000, .sqlite),
        // An invalid statement the mock rejects → transaction rolls back.
        .{ .id = 2001, .name = "bad", .up = &.{"TOTALLY NOT SQL"} },
    };
    try testing.expectError(Error.BadStatement, Migrator.run(backend, &migs, 1_700_000_000));

    // 2000 applied; 2001 NOT recorded (rolled back).
    var row: contract.Row = .{};
    try testing.expect(try backend.queryOne("SELECT 1 FROM zorm_migrations WHERE id = ?", &.{.{ .int = 2000 }}, &row));
    try testing.expect(!try backend.queryOne("SELECT 1 FROM zorm_migrations WHERE id = ?", &.{.{ .int = 2001 }}, &row));
}
